import Layout from "@/components/Layouts/Layout";
import HomeHero from "@/components/home/HomeHero";
import Head from "next/head";

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <HomeHero />
      </div>
    </>
  );
};

export default HomePage;

HomePage.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};
